package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

enum class WorkStepType(val id: String, val labelEn: String, val labelAr: String, val icon: String) {
    CLICK_BUTTON("click_button", "Click Button", "نقر زر", "🖱️"),
    SCROLL("scroll", "Scroll Page", "تمرير الصفحة", "📜"),
    FILL_FIELD("fill_field", "Fill Form Field", "ملء حقل استمارة", "✍️"),
    CHECK_BOX("check_box", "Check Box / Terms", "تحديد مربع / الشروط", "☑️"),
    SELECT_OPTION("select_option", "Select Option / Radio", "اختيار خيار / راديو", "🔘"),
    DELAY("delay", "Human Delay / Wait", "انتظار طبيعي", "⏱️"),
    EXTRACT_ADAPT("extract_adapt", "Extract & Reason", "استخراج ذكي وتكيّف", "🧠")
}

data class WorkStep(
    val id: String = UUID.randomUUID().toString(),
    val type: WorkStepType = WorkStepType.CLICK_BUTTON,
    val targetType: String = "auto", // "auto", "text", "selector", "id", "tag"
    val targetValue: String = "", // e.g., "Submit", "Continue", "Get $1000", "input[type=email]"
    val fieldSource: String = "identity", // "identity", "extracted_info", "custom", "page_extracted"
    val fieldKey: String = "email", // "email", "firstName", "lastName", "fullName", "phone", "address", "city", "state", "postalCode", "custom"
    val customValue: String = "",
    val scrollDirection: String = "down", // "down", "up", "to_element", "to_bottom"
    val scrollAmount: Int = 350,
    val delayMs: Long = 1200L,
    val description: String = ""
)

@Entity(tableName = "work_templates")
data class WorkTemplateEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val name: String,
    val description: String = "",
    val targetCategory: String = "Smart Auto", // e.g., "Email Submit", "Survey / Quiz", "Lead Gen", "Smart Auto"
    val isAutoGenerated: Boolean = false,
    val stepsJson: String = "[]",
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)

data class ActionMapStep(
    val order: Int,
    val title: String,
    val type: String, // "click", "scroll", "fill", "check", "select", "extract"
    val target: String,
    val status: String = "pending", // "pending", "executing", "done", "skipped"
    val details: String = ""
)
